spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wleek2@gmail.com
    password: rjsxo..12
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
